name: aliyun sso
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Nojekyll
        run: touch ./public/.nojekyll

      - name: Deploy
        uses: saltbo/uptoc@master
        with:
          driver: oss
          region: ${{ secrets.REGION }}
          bucket: ${{ secrets.BUCKET }}
          exclude: .cache,test
          dist: public
        env:
          UPTOC_UPLOADER_AK: ${{ secrets.KEYID }}
          UPTOC_UPLOADER_SK: ${{ secrets.KEYSECRET }}