name: deploy
on:
  push:
    branches:
      - content
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/hugo-algolia2@v1
        with:
          input: "./posts/**"
          output: "./algolia.json"
          index: ${{ secrets.ALGOLIA_INDEX }}
          apikey: ${{ secrets.ALGOLIA_APIKEY }}
          appid: ${{ secrets.ALGOLIA_APPID }}

