name: deploy
on:
  push:
  workflow_dispatch:

jobs:
  trigger-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_E15mS0ZdXW0c25fWN9oLfeRXPFXA/spfa5EOiQS
  generate-algolia:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: caibingcheng/hugo-algolia2@v1
        with:
          input: "./content/**"
          output: "./algolia.json"
          index: ${{ secrets.ALGOLIA_INDEX }}
          apikey: ${{ secrets.ALGOLIA_APIKEY }}
          appid: ${{ secrets.ALGOLIA_APPID }}

