name: deploy
on:
  push:
    branches:
      - master
      - content
      - LoveIt
      - live2d
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_E15mS0ZdXW0c25fWN9oLfeRXPFXA/bpPhhsyZZS
      # - uses: actions/checkout@v2
      #   with:
      #     ref: master
      #     submodules: true  # Fetch Hugo themes (true OR recursive)
      #     fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      # - name: Update Submodules
      #   run: . submodule.sh

      # - name: Setup Hugo
      #   uses: peaceiris/actions-hugo@v2.3.1
      #   with:
      #     hugo-version: '0.83.1'
      #     # extended: true

      # - name: Build
      #   run: hugo --minify

      # - name: Nojekyll
      #   run: touch ./public/.nojekyll

      # # - name: Deploy-githubpage
      # #   uses: peaceiris/actions-gh-pages@v2.5.1
      # #   env:
      # #     ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      # #     EXTERNAL_REPOSITORY: caibingcheng/caibingcheng.github.io
      # #     PUBLISH_BRANCH: master
      # #     PUBLISH_DIR: ./public

      # - name: Deploy-oss
      #   uses: fangbinwei/aliyun-oss-website-action@v1
      #   with:
      #       accessKeyId: ${{ secrets.KEYID }}
      #       accessKeySecret: ${{ secrets.KEYSECRET }}
      #       bucket: ${{ secrets.BUCKET }}
      #       # e.g. "oss-cn-shanghai.aliyuncs.com"
      #       endpoint: ${{ secrets.ENDPOINT }}
      #       folder: public

      # # - name: Deploy-ldftp
      # #   uses: sebastianpopp/ftp-action@releases/v2
      # #   with:
      # #     host: ${{ secrets.FTP_SERVER }}
      # #     user: ${{ secrets.FTP_USERNAME }}
      # #     password: ${{ secrets.FTP_PASSWORD }}
      # #     localDir: "public"
      # #     remoteDir: "www"

      # - name: Post Urls
      #   run: . urls.sh
