name: aliyun sso
# name: landui vm
on:
  push:
    branches:
      - master
      - content

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Update Content
        run: cd ./content && git pull origin content

      - name: Update Live2d
        run: cd ./static/live2d && git pull origin live2d

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Nojekyll
        run: touch ./public/.nojekyll

      - name: Deploy
        uses: fangbinwei/aliyun-oss-website-action@v1
        with:
            accessKeyId: ${{ secrets.KEYID }}
            accessKeySecret: ${{ secrets.KEYSECRET }}
            bucket: ${{ secrets.BUCKET }}
            # e.g. "oss-cn-shanghai.aliyuncs.com"
            endpoint: ${{ secrets.ENDPOINT }}
            folder: public

        # uses: sebastianpopp/ftp-action@releases/v2
        # with:
        #   host: ${{ secrets.FTP_SERVER }}
        #   user: ${{ secrets.FTP_USERNAME }}
        #   password: ${{ secrets.FTP_PASSWORD }}
        #   localDir: "public"
        #   remoteDir: "~/web/"
        #   options: "--delete --asci"

      - name: Post Urls
        run: . urls.sh